4.6 Валидация данных в формах
thinknetica-django-lab-03/petrovskydv pull request #47
Opened 2021-06-11 07:57 UTC by petrovskydv

closes #27

2021-06-11 18:30 UTC, morgangt requested changes

2021-06-11 18:30 UTC, morgangt commented on main/models.py
> +
в файле models.py должны быть код которые относятся к моделям этот код относиться к отправке email
данные функции можно перенести например в файл utils.py
или можно превратить эту функцию в lambda выражение и стразу использовать на 57 строке
```
def raise_(ex):
    raise ex

lambda: raise_(ValidationError('Вам нет 18!')) if (now().year - birthday.year) < 18 else pass
```

2021-06-12 07:03 UTC, petrovskydv commented on main/models.py
> +
перенес функцию валидации в utils.py, но я не понял почему это относится к отправке email, если об отправке писем речь идет только в 6 модуле.

2021-06-14 09:46 UTC, morgangt approved these changes

2021-06-15 08:17 UTC, merged